runtime: php

api_version: '1.0'
env: flex

runtime_config:
    document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
    - .env


threadsafe: true
env_variables:
    APP_KEY: 'base64:+1DXV4bEv8zobcenrdfBF2B/FsO8QbwYiEmbtbiNaRE='
    APP_LOG: errorlog
automatic_scaling:
    cool_down_period: 120s
    min_num_instances: 1
    max_num_instances: 2
    cpu_utilization:
        target_utilization: 0.5
network: {}
