# Use root/example as user/password credentials
version: '3.1'

services:

    db:
        image: mariadb:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 2929899+-+
        volumes:
          - ./databasevol:/var/lib/mysql
        ports:
          - 3306:3306
